server:
  port: 8888
spring:
  datasource:
     driver-class-name: com.mysql.jdbc.Driver
     url: jdbc:mysql://127.0.0.1:3306/account?useUnicode=true&characterEncoding=UTF-8
     username: root
     password:
     tomcat:
       max-wait: 10000
       max-active: 10
       initial-size: 2
       min-idle: 1
       max-idle: 3
  jackson.property-naming-strategy: CAMEL_CASE_TO_LOWER_CASE_WITH_UNDERSCORES

  rabbitmq:
      host: localhost
      port: 5672
      username: guest
      password: guest
      publisher-confirms: true
      publisher-returns: true
mybatis:
  configuration:
      map-underscore-to-camel-case: true
      default-fetch-size: 100
      default-statement-timeout: 30